### ISSUE TITLE
update your readme, it has `libhycov.so` instead of `libhych.so`

### ISSUE THREAD

**Issue by daUnknownCoder** [DreamMaoMao/hych#2]
[your readme](https://github.com/DreamMaoMao/hych?tab=readme-ov-file#using-cmake)

3 line after this line -> `bash install.sh` ending

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hych/assets/30348075/aed7e4b2-15b5-4aa6-82c4-182c32b7dff3)

Thank you for reminding me,have fixed
